### ISSUE TITLE
cuanto-config.properties file not exits

### ISSUE THREAD

**Issue by VivekLande** [ttop/cuanto#15]
Hi, 
I have setup cuanto tool on Ubuntu OS as per installation guidline of cuanto . After setup completed when I started jetty server its throwing exception that cuanto-config.properties  doesnt exits at  ~/.grails  directory. please help.
Thanks in advance.

**Comment by ttop** [comment]
That is an optional file, so I don't know why it's doing that without more detailed information. Without seeing a stack trace or more detailed information, my guess is that you haven't provided a cuanto-db.groovy file with correct database information and that is the primary error .

https://github.com/ttop/cuanto/blob/master/INSTALL.mkdn

**Comment by VivekLande** [comment]
I have copied cuanto-db.groovy file with correct database info..find attached file.
[Cuanto.txt](https://github.com/ttop/cuanto/files/100305/Cuanto.txt)

**Comment by ttop** [comment]
Please review the instructions under "Running Locally". Don't execute jetty directly, you run `grails run-app`. https://github.com/ttop/cuanto/blob/master/INSTALL.mkdn

## Running Locally

_Running locally is only recommended if you are just wanting to try out Cuanto. Don't run a production Cuanto server using this method._

To run locally, you want to have [Grails](http://grails.org) 1.3.7 installed. Copy `cuanto-db.groovy` file to the `~/.grails` directory (or the Windows equivalent) and modify as described below. Copy your JDBC driver to the `grails/lib` directory. Then in the `cuanto/grails` directory, type `grails upgrade`. Then you can start Cuanto by executing `grails run-app`. Once it has started, the URL to reach Cuanto will be displayed, usually `http://localhost:8080/cuanto`.

**Comment by VivekLande** [comment]
Thank you very much  sir..!!

**Comment by VivekLande** [comment]
sir please tell me to configure cuanto with Maven which changes I will need at Test case level .
How I will implement cuanto for my test case.

**Comment by ttop** [comment]
I suggest you review the [grails 1.3.7 docs](https://grails.github.io/grails-doc/1.3.7/guide/single.html) regarding maven integration and testing.
