### ISSUE TITLE
enhancement: Allow uploading results as a zip/tarball.

### ISSUE THREAD

**Issue by paljsingh** [ttop/cuanto#18]
I am trying to publish my project's unit test (junit) results to cuanto.
The number of unit tests is huge (over 20000) and publishing the results to cuanto takes a long time (over 30 minutes). I am using the ant task for publishing the results.

Going through the json api documentation it seems that the client needs to make multiple http requests per test outcome, even after moving the client machine in the same subnet as the cuanto server, I am not able to bring the publish time by a significant amount.

Is there any existing api I can use to push the entire test result in a single http request (in case I missed it) ?
if not, please provide a mechanism to upload the tarball/zip of the junit xmls for quicker result uplaod.

**Comment by ttop** [comment]
Hi, no there's not an API to submit the entire test results as one request. I am not able to add new features at this time, but the source is available here if you wish to explore adding that feature.
