### ISSUE TITLE
Suggestion: API Should be RESTfull.. use HTTP Verbs in and remove actions from Resource names

### ISSUE THREAD

**Issue by andreasmarkussen** [ttop/cuanto#21]
I just looked at the API and I could see that the API Urls contains action names, and it should contain Resource names. 

i.e. 

    HTTP POST to http://<cuantourl>/api/addTestRun 

Should be

    POST to http://<cuantourl>/api/TestRuns

And /api/getTestRun should be 

    GET to  http://<cuantourl>/api/TestRun/<testRunId>

[See API Documents:](https://github.com/ttop/cuanto/wiki/Cuanto-JSON-API)

Would you accept Pull Requests for this? 

And perhaps we should create a "new api" called 
    http://<cuantourl>/rest/TestRuns

**Comment by ttop** [comment]
Thanks for your interest. Cuanto is no longer under active development. Please feel free to fork the code and do as you wish.

**Comment by andreasmarkussen** [comment]
OK! Did you find another tool that you liked better? or did you just not have the need anymore?

**Comment by ttop** [comment]
My role changed to one that is no longer involved in testing or result tracking, so I no longer have any time allocated to maintain it nor any personal need for it.
